name: "GitHub Actions Find Domain"

on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [main]
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Working
        env:
          DOMAIN: ${{ secrets.DOMAIN}}
        run: python main.py
